import { logger } from '../lib/logger.js';
import { sanitizeMarkdown } from '../lib/sanitize.js';

// Lazy singleton browser — puppeteer is optional so the handle is typed as `any`.

let browserInstance: any = null;
let browserLaunching: Promise<any> | null = null;

async function getBrowser(): Promise<any> {
  if (browserInstance) return browserInstance;

  // Prevent multiple concurrent launches during startup
  if (browserLaunching) return browserLaunching;

  browserLaunching = (async () => {
    try {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore – puppeteer is an optional dependency; guarded at runtime
      const puppeteer = await import('puppeteer');
      const browser = await puppeteer.default.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
        executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || undefined,
      });

      // If the browser crashes or is killed, clear the singleton so next call relaunches.
      browser.on('disconnected', () => {
        logger.warn('Puppeteer browser disconnected — will relaunch on next PDF request');
        browserInstance = null;
        browserLaunching = null;
      });

      browserInstance = browser;
      browserLaunching = null;
      logger.info('Puppeteer browser launched (singleton)');
      return browser;
    } catch {
      browserLaunching = null;
      throw new Error('PDF generation unavailable (puppeteer not installed)');
    }
  })();

  return browserLaunching;
}

/** Graceful shutdown — close the browser if it's running. */
export async function closeBrowser(): Promise<void> {
  if (browserInstance) {
    await browserInstance.close().catch(() => {});
    browserInstance = null;
    browserLaunching = null;
  }
}

export interface PdfContractData {
  title:       string;
  status:      string;
  valueCents?: number | null;
  currency?:   string;
  orgName:     string;
  bodyMd?:     string;
  version?:    string;
  generatedAt: Date;
}

function escapeHtml(s: string): string {
  return s.replace(/[<>&"]/g, c => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;' }[c]!));
}

function buildHtml(data: PdfContractData): string {
  const safeTitle   = escapeHtml(data.title);
  const safeOrg     = escapeHtml(data.orgName);
  const safeStatus  = escapeHtml(data.status);
  const bodyContent = data.bodyMd ? sanitizeMarkdown(data.bodyMd) : '';
  const valueStr    = data.valueCents != null
    ? `${(data.valueCents / 100).toLocaleString('en-US', { style: 'currency', currency: data.currency || 'USD' })}`
    : 'N/A';

  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<style>
  body { font-family: 'Helvetica Neue', Arial, sans-serif; margin: 40px; color: #222; font-size: 12pt; }
  h1 { font-size: 20pt; color: #1a1a2e; border-bottom: 2px solid #1a1a2e; padding-bottom: 8px; }
  .meta { display: flex; gap: 24px; margin: 16px 0; font-size: 10pt; color: #555; }
  .meta span { font-weight: bold; color: #222; }
  .body { margin-top: 24px; line-height: 1.6; }
  .footer { margin-top: 40px; font-size: 9pt; color: #888; border-top: 1px solid #ddd; padding-top: 8px; }
</style>
</head><body>
<h1>${safeTitle}</h1>
<div class="meta">
  <div>Organization: <span>${safeOrg}</span></div>
  <div>Status: <span>${safeStatus}</span></div>
  <div>Value: <span>${valueStr}</span></div>
  ${data.version ? `<div>Version: <span>${escapeHtml(data.version)}</span></div>` : ''}
</div>
<div class="body">${bodyContent}</div>
<div class="footer">Generated by ContractCanvas on ${data.generatedAt.toISOString()}</div>
</body></html>`;
}

export async function generateContractPdf(data: PdfContractData): Promise<Buffer> {
  const browser = await getBrowser();
  const page = await browser.newPage();
  try {
    await page.setContent(buildHtml(data), { waitUntil: 'networkidle0' });
    const pdf = await page.pdf({ format: 'A4', margin: { top: '20mm', bottom: '20mm', left: '20mm', right: '20mm' }, printBackground: false });
    return Buffer.from(pdf);
  } finally {
    await page.close();
  }
}
