// scripts/config-to-env.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Assume this script lives in ROOT/scripts/
const repoRoot = path.resolve(__dirname, '..');
const configPath = path.join(repoRoot, 'config.json');

// IMPORTANT: keep Prisma CLI DB URL separate to avoid conflicts
const prismaEnvPath = path.join(repoRoot, 'apps', 'api', 'prisma', '.env'); // <— CLI env (DATABASE_URL only)
const apiEnvPath = path.join(repoRoot, 'apps', 'api', '.env');              // <— API runtime env (NO DATABASE_URL)
const composeEnvPath = path.join(repoRoot, 'infra', '.env');                // <— Docker Compose env

// --- Load config.json ---
let cfg;
try {
  const raw = fs.readFileSync(configPath, 'utf8');
  cfg = JSON.parse(raw);
  if (!cfg.db) throw new Error('config.json is missing the "db" section.');
} catch (e) {
  console.error(`[config:env] Failed to read or parse ${configPath}:`, e?.message ?? e);
  process.exit(1);
}

// Shorthands with sensible defaults
const app = cfg.app ?? {};
const db = cfg.db ?? {};
const s3 = cfg.s3 ?? {};
const stripe = cfg.stripe ?? {};
const jwt = cfg.jwt ?? {};

const appEnv = app.env ?? 'development';
const appPort = Number(app.port ?? 3333);

// --- DB pieces ---
const dbUser = db.user ?? 'postgres';
const dbPass = db.password ?? 'postgres';
const dbName = db.name ?? 'contractcanvas_db';
const dbPort = Number(db.port ?? 5432); // your config uses 5432
const dbHost = 'localhost';             // Prisma CLI connects to the host-mapped port
const dbContainerName = db.container_name ?? 'contractcanvas-postgres';

// --- Compose Prisma DATABASE_URL (for Prisma CLI only) ---
const DATABASE_URL =
  `postgresql://${encodeURIComponent(dbUser)}:${encodeURIComponent(dbPass)}` +
  `@${dbHost}:${dbPort}/${encodeURIComponent(dbName)}?schema=public`;

// --- Helper: safe write with mkdirp ---
function writeFileEnsured(filePath, content, label) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Wrote ${label}: ${path.relative(repoRoot, filePath)}`);
}

// --- 1) Write apps/api/prisma/.env (Prisma CLI) ---
// Keep ONLY DATABASE_URL here to avoid Prisma “conflicting env vars” errors.
const prismaEnvContent = `# Generated by scripts/config-to-env.mjs (for Prisma CLI)
# Connects to the host port mapped by Docker Compose
DATABASE_URL="${DATABASE_URL}"
`;
writeFileEnsured(prismaEnvPath, prismaEnvContent, 'Prisma CLI env');

// --- 2) Write apps/api/.env (API runtime) ---
// DO NOT put DATABASE_URL here. Your runtime can read DB from config.json,
// and prisma.ts can pass it via datasources or config fallback.
const apiEnvContent = `# Generated by scripts/config-to-env.mjs (for API runtime)
APP_ENV=${appEnv}
APP_PORT=${appPort}

# JWT
JWT_SECRET="${jwt.secret ?? ''}"

# S3 / MinIO
S3_ENDPOINT="${s3.endpoint ?? ''}"
S3_REGION="${s3.region ?? ''}"
S3_BUCKET="${s3.bucket ?? ''}"
S3_ACCESS_KEY="${s3.accessKey ?? ''}"
S3_SECRET_KEY="${s3.secretKey ?? ''}"
S3_FORCE_PATH_STYLE=${Boolean(s3.forcePathStyle ?? true)}

# Stripe
STRIPE_SECRET_KEY="${stripe.secretKey ?? ''}"
STRIPE_WEBHOOK_SECRET="${stripe.webhookSecret ?? ''}"

# NOTE: DATABASE_URL is intentionally omitted to prevent conflicts with Prisma CLI.
`;
writeFileEnsured(apiEnvPath, apiEnvContent, 'API runtime env');

// --- 3) Write infra/.env (Docker Compose) ---
// This is typically consumed by docker-compose.yml for DB + services.
const composeEnvContent = `# Generated by scripts/config-to-env.mjs (for Docker Compose)

# --- Postgres ---
POSTGRES_USER=${dbUser}
POSTGRES_PASSWORD=${dbPass}
POSTGRES_DB=${dbName}
POSTGRES_PORT=${dbPort}
POSTGRES_CONTAINER_NAME=${dbContainerName}

# --- S3 (optional if your compose wires these to the API container) ---
S3_ENDPOINT=${s3.endpoint ?? ''}
S3_REGION=${s3.region ?? ''}
S3_BUCKET=${s3.bucket ?? ''}
S3_ACCESS_KEY=${s3.accessKey ?? ''}
S3_SECRET_KEY=${s3.secretKey ?? ''}
S3_FORCE_PATH_STYLE=${Boolean(s3.forcePathStyle ?? true)}

# --- Stripe (optional: wire to API service if needed) ---
STRIPE_SECRET_KEY=${stripe.secretKey ?? ''}
STRIPE_WEBHOOK_SECRET=${stripe.webhookSecret ?? ''}

# --- API (optional) ---
APP_ENV=${appEnv}
APP_PORT=${appPort}
`;
writeFileEnsured(composeEnvPath, composeEnvContent, 'Compose env');

// --- Optional: detect conflicting root .env DATABASE_URL and warn ---
const rootEnvPath = path.join(repoRoot, '.env');
if (fs.existsSync(rootEnvPath)) {
  try {
    const rootEnv = fs.readFileSync(rootEnvPath, 'utf8');
    if (/^DATABASE_URL\s*=.+/m.test(rootEnv)) {
      console.warn(
        '\n[config:env] Warning: root .env defines DATABASE_URL. ' +
        'Prisma may report a conflict. Consider removing DATABASE_URL from the root .env ' +
        'so only apps/api/prisma/.env provides it.\n'
      );
    }
  } catch {
    // ignore
  }
}

console.log('[config:env] Environment files generated successfully.');